### ISSUE TITLE
考虑使用HttpClient

### ISSUE THREAD

**Issue by Berrysoft** [chenxuuu/add-one-second-UWP#3]
现有的POST和GET是自己造的轮子多不方便，试试[HttpClient](https://docs.microsoft.com/zh-cn/uwp/api/Windows.Web.Http.HttpClient)

**Comment by Berrysoft** [comment]
到最后也决定不改了吗😂

**Comment by chenxuuu** [comment]
目前代码没有请求http的部分

**Comment by Berrysoft** [comment]
确实，服务器没了
