### ISSUE TITLE
进入应用始终显示loading

### ISSUE THREAD

**Issue by OYFSSS** [chenxuuu/add-one-second-UWP#4]
不知道是否是网站出了什么问题

**Comment by XU0621** [comment]
我也是，不会是停止服务了吧。。

**Comment by arenekosreal** [comment]
内置的接口 https://angry.im/l/life 已经失效了，只有等作者解决了

**Comment by CsyBarry** [comment]
希望作者尽快修复

**Comment by chenxuuu** [comment]
源站炸了，要修的话只能我自己再开个计数器。。



---原始邮件---
发件人: "CsyBarry"<notifications@github.com&gt;
发送时间: 2020年8月17日(周一) 晚上7:22
收件人: "chenxuuu/add-one-second-UWP"<add-one-second-UWP@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [chenxuuu/add-one-second-UWP] 进入应用始终显示loading (#4)




 
希望作者尽快修复
